Brandonnguyenn27/issue23
SCE-Development/spartan-compass pull request #39
Opened 2024-03-30 03:21 UTC by brandonnguyenn27

2024-03-31 08:09 UTC, gursheyss requested changes

2024-03-31 08:09 UTC, gursheyss commented on src/routes/course/[id]/+page.svelte
We should only show professors on this page, not reviews

2024-03-31 08:09 UTC, gursheyss commented on src/lib/components/Course Page/ProfessorCard.svelte
> +	}
```suggestion
	let [firstName, ...rest] = professor.name.split(' ');
	let lastName = rest.pop() || firstName;
	let professorNameRoute = `${firstName}-${lastName}`;
```

2024-03-31 17:54 UTC, brandonnguyenn27 commented
Not too worried about frontend styling right now because it will probably change in the near future- just focusing on displaying the correct data

2024-04-02 21:56 UTC, gursheyss approved these changes

2024-04-02 21:57 UTC, merged